COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_SRCDIRS := src
CXXFLAGS += -DESPRESSIO_WIFI
CXXFLAGS += -DESPRESSIO_WIFI_VERSION_MAJOR=1
CXXFLAGS += -DESPRESSIO_WIFI_VERSION_MINOR=0
CXXFLAGS += -DESPRESSIO_WIFI_VERSION_PATCH=0
CXXFLAGS += -DESPRESSIO_WIFI_VERSION_STRING=\"1.0.0\"