COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_SRCDIRS := src
CXXFLAGS += -DESPRESSIO_WIFI
CXXFLAGS += -DESPRESSIO_WIFI_VERSION_MAJOR=0
CXXFLAGS += -DESPRESSIO_WIFI_VERSION_MINOR=2
CXXFLAGS += -DESPRESSIO_WIFI_VERSION_PATCH=0
CXXFLAGS += -DESPRESSIO_WIFI_VERSION_STRING=\"0.2.0\"
