name=ESPressio-WiFi
version=1.0.0
author=Simon J. Stuart
maintainer=Simon J. Stuart
sentence=WiFi Component Library intended for use with ESP microcontrollers
paragraph=This library is intended to be used with ESP microcontrollers. It is designed to allow the user to very easily design, structure, and develop your embedded programs using the Event Pattern. This library is intended to be used with PlatformIO and the Arduino framework.
category=Communication
url=https://espressio.org
architectures=esp32,esp8266
