cmake_minimum_required(VERSION 3.16)
project(ESPressioWiFiTests LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
include(FetchContent)
FetchContent_Declare(ESPressioObservable GIT_REPOSITORY https://github.com/ESPressio-Development-Platform/ESPressio-Observable.git GIT_TAG 3.0.2 GIT_SHALLOW TRUE)
FetchContent_Declare(ESPressioSerializable GIT_REPOSITORY https://github.com/ESPressio-Development-Platform/ESPressio-Serializable.git GIT_TAG main GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(ESPressioObservable ESPressioSerializable)
add_executable(espressio_wifi_tests test_wifi.cpp)
target_include_directories(espressio_wifi_tests PRIVATE ../src ${espressioobservable_SOURCE_DIR}/src ${espressioserializable_SOURCE_DIR}/src)
enable_testing()
add_test(NAME ESPressioWiFiTests COMMAND espressio_wifi_tests)
